# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gb-container

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crlyr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8C49F072CA04411EBE32A52C1BD09BBC }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_158D0D1C28294F5FB6B5152B5592C738 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crlyr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8C49F072CA04411EBE32A52C1BD09BBC }}/guestbook:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gb-container'
          slot-name: 'con-staging'
          images: 'crlyr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8C49F072CA04411EBE32A52C1BD09BBC }}/guestbook:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0EF8048C8AA14CC1AC865B2BD58AC025 }}